# Build stage
FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o url-shortener ./cmd

# Final stage
FROM golang:1.22-alpine
WORKDIR /app
COPY --from=builder /app/url-shortener .
CMD ["./url-shortener"]