name: ${PROJECT_NAME:-preview}
services:
  app:
    image: ${IMAGE_REF}
    container_name: ${PROJECT_NAME}-app
    environment:
      SUBDOMAIN: ${SUBDOMAIN}
      IMAGE_REF: ${IMAGE_REF}
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      - edge

networks:
  edge:
    external: true
