services:
  traefik:
    image: traefik:latest
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "8081:8080"   # Dashboard
    volumes:
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - edge
networks:
  edge:
    name: edge
    driver: bridge
